name: vr_iscool
description: "Um projeto de CRUD de escolas."

publish_to: 'Deivide Paulino' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  result_dart: ^1.0.6
  dio: ^5.2.1+1
  lottie: ^2.4.0
  flutter_modular: ^5.0.3
  asp: ^1.3.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0




  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.14
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logotipo/
    - assets/animations/
    - assets/profile/
